### ISSUE TITLE
HU-5 Obtener información de una tarea

### ISSUE THREAD

**Issue by MariaLu98** [carlostiguaque/MISW-4204-Drones#5]
Desarrollar y exponer un servicio REST (GET) para obtener la información de una tarea de edición específica. El usuario debe proveer el token de autenticación para realizar dicha operación. Además, el servicio REST (GET) debe permitir recuperar/descargar el video
procesado de un usuario, suministrando una URL para el archivo consultado. En caso de que el vídeo no se encuentre editado, no contará con una URL asociada.

**Comment by jvillada97** [comment]
El video puede ser recuperado directamente desde postman
